{
  "plugins": [
    "jest"
  ],
  "env": {
    "node": true,
    "es2021": true
  },
  "extends": [
    "airbnb-base",
    "plugin:jest/recommended"
  ],
  "overrides": [],
  "parserOptions": {
    "ecmaVersion": 2022,
    "sourceType": "module"
  },
  "rules": {
    "no-console": 0,
    "import/extensions": [
      "error",
      {
        "ignorePackages": true,
        "js": "never"
      }
    ],
    "no-underscore-dangle": [
      2,
      { "allow": ["__filename", "__dirname"] }
    ]
  }
}
